@startuml temperature-monitoring-application-protocol-example-3-request-unknown-room-temperature
skinparam boxPadding 100
skinparam maxMessageSize 150
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250
autonumber

!pragma teoz true

title "Temperature monitoring application protocol - Example 3 - Request unknown room temperature"

participant "Emitter 1" as e1
participant "Emitter 2" as e2
participant "Server" as s
participant "Operator" as o

== Emit temperature ==

e1 --> e1: <&clock> ... <&clock> ... <&clock> ...
e1 -[#red]> s: TEMP Kitchen 21.2
s -> s: Store the room's temperature

== Request temperature of an unknown room ==

o -[#blue]> s: REQ_TEMP Garage
s -[#blue]> o: ERROR 1

legend
**Legend**

Types of communication and patterns used in the application.

| **Color** | **Type**  | **Pattern**      |
| <#red>    | Multicast | Fire and forget  |
| <#blue>   | Unicast   | Request-response |
endlegend

@enduml
