@startuml sequence-diagram-of-the-public-private-keys-communication-mechanism
skinparam boxPadding 100
skinparam maxMessageSize 300
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250
autonumber

!pragma teoz true

title "Sequence diagram of the public/private keys communication mechanism"

actor "Alice" as alice
actor "Bob" as bob

note over alice, bob: Key-pair generation

alice -> alice: Generate key pair
bob -> bob: Generate key pair

...

note over alice, bob: Alice sends a message to Bob so that only Bob can read it.

alice -> bob: Request Bob's public key
bob --> alice: Get Bob's public key

alice -> alice: Encrypt a message using Bob's public key
alice -> bob: Send the encrypted message to Bob

bob -> bob: Decrypt the message using Bob's private key
bob -> bob: Only Bob can read the message sent by Alice

...

note over alice, bob: Bob digitally signs a message.\nEveryone can attest Bob is the author.

bob -> bob: Encrypt a message using Bob's private key
bob -> alice: Send the encrypted message to Alice
alice -> bob: Request Bob's public key
bob --> alice: Get Bob's public key
alice -> alice: Decrypt the message using Bob's public key
alice -> alice: Alice can verify the message was authored by Bob
@enduml
