@startuml ssh-authentication-process

skinparam boxPadding 100
skinparam maxMessageSize 300
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250
autonumber

!pragma teoz true

title "SSH authentication process"

actor "User" as user
participant "SSH Client" as client
participant "SSH Server" as server

user -> client: Start SSH session
user -> client: Provide credentials
client -> server: Open SSH connection
server --> client: SSH server banner
client -> server: Authenticate (public key)
server --> client: Request public key
client --> server: Send public key
server --> client: Public key accepted
client -> server: Authenticate (private key)
server --> client: Request challenge
client --> server: Sign challenge
server --> client: Challenge response
server --> client: Authentication successful
user -> client: Execute SSH commands
client -> server: Send SSH commands
server -> client: Execute commands
client --> user: Display output
@enduml
