@startuml validation-model-based-on-the-last-modified-header-part-2
skinparam boxPadding 100
skinparam maxMessageSize 150
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250

title "Validation model based on the Last-Modified header - part 2/4"

participant "Client 1" as client1
participant "Server" as server
participant "Client 2" as client2

== Get data that have not been modified ==

|||

note over client1, server
GET /users/1 HTTP/1.1
Host: example.com
Accept: application/json
If-Modified-Since: Tue, 20 Feb 2022 22:00:00 GMT
end note
client1 -> server: New request (at 22 Feb 2022, 23:05:00)

|||

server -> server: Check in cache...\nCache hit; no need to store request in cache.

note over client1, server
HTTP/1.1 304 Not Modified
Date: Tue, 22 Feb 2022 23:05:21 GMT
end note
server -> client1: The information has not changed

@enduml
