@startuml

title "Validation based on the Last-Modified header"

participant Client
participant Server

== First request ==

note over Client, Server
GET /index.html HTTP/1.1
Host: example.com
Accept: text/html
end note
Client -> Server: Initial request (at 22 Feb 2022, 22:22:00)

|||

note over Client, Server
HTTP/1.1 200 OK
Content-Type: text/html
Content-Length: 1024
Date: Tue, 22 Feb 2022 22:22:22 GMT
Last-Modified: Tue, 20 Feb 2022 22:00:00 GMT
end note
Server -> Client: Response

@enduml
