@startuml
left to right direction
skinparam packageStyle rectangle

title "Reverse proxy"

actor "Client 1" as client1
actor "Client 2" as client2
actor "Client N" as clientN

cloud "Internet" as internet {
    (client1) -- internet
    (client2) -- internet
    (clientN) -- internet
}

rectangle "Servers LAN" as serverLan {

    actor "Server 1" as server1
    actor "Server 2" as server2
    actor "Server N" as serverN

    rectangle "Reverse proxy" as reverseProxy {
        internet -- (Enter the LAN)
        (Enter the LAN) -- server1
        (Enter the LAN) -- server2
        (Enter the LAN) -- serverN
    }
}
@enduml
