@startuml practical-work-3-architecture
left to right direction
skinparam componentStyle rectangle
skinparam ComponentPadding 10
skinparam BoxPadding 20

title Practical Work 2 - UDP network application - Architecture

interface "Thermometer 1" as therm1
interface "Humidity 1" as hum1
interface "Thermometer 2" as therm2
interface "Pressure 1" as press1

component WeatherStation as ws {
    portin 9876
    portout 1234

    component "Sensors Worker" as sensorsWorker
    component "Clients Worker" as clientsWorker

    9876 -left[#red]-> sensorsWorker
    1234 <-[#blue]-> clientsWorker
}

component "Client 1" as client1
component "Client 2" as client2

therm1 -[#red]-> 9876 : 239.0.0.1
therm2 -[#red]-> 9876 : 239.0.0.1
hum1 -[#red]-> 9876 : 239.0.0.2
press1 -[#red]-> 9876 : 239.0.0.3

client1 <-up[#blue]-> 1234 : localhost
client2 <-up[#blue]-> 1234 : localhost

legend right
|Color| Type |
|<#FF0000>| Multicast - Fire and Forget |
|<#0000FF>| Unicast - Request Response |
endlegend
@enduml
