@startuml client-server-workflow
hide footbox

participant "TCP Server" as server
participant "TCP Client" as client

server -> server : **Create** a socket \n (class ServerSocket)

server -> server : **Bind** the socket to \n an IP and a port (e.g. 1234)

loop Server listens for incoming connections
    client -> client : **Create** a socket \n (class Socket)
    client -> server : **Connect** to the server \n using the IP and port 1234
    server -> client : **Accept** the connection \n and create a new client socket \n on a random port
    server <-> client : **Read and write** data \n from/to the socket
    ...
    client -> server : **Close** the connection
end

server -> server : **Close** the socket
@enduml
