@startuml DAI_Protocol

title DAI Protocol Sequence Diagram

actor Client
actor Server

Client --> Server : Establish Connection
Server -> Client : OK

Client -> Server : SEND GET /data/file.txt
Server -> Client : FILE /data/file.txt (Binary Data)

Server --> Client : Close Connection

...

Client --> Server : Establish Connection
Server -> Client : OK

Client -> Server : SEND GET /nonexistentfile.txt
Server -> Client : ERROR 404
Server --> Client : Close Connection

...

Client --> Server : Establish Connection
Server -> Client : OK

Client -> Server : QUIT
Client --> Server : Close Connection
@enduml