@startuml forward-proxy

left to right direction
skinparam packageStyle rectangle
skinparam boxPadding 100
skinparam maxMessageSize 300
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250

!pragma teoz true

title "Forward proxy"

actor "Server 1" as server1
actor "Server 2" as server2
actor "Server N" as serverN

rectangle "Clients LAN" as clientsLan {
    actor "Client N" as clientN
    actor "Client 2" as client2
    actor "Client 1" as client1

    rectangle "Forward proxy" as forwardProxy {
        client1 -- (Exit the LAN)
        client2 -- (Exit the LAN)
        clientN -- (Exit the LAN)
    }
}

cloud "Internet" as internet {
    (Exit the LAN) -- internet
    internet -- (server1)
    internet -- (server2)
    internet -- (serverN)
}
@enduml
