@startuml http-without-the-host-header

skinparam boxPadding 100
skinparam maxMessageSize 300
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250
autonumber

!pragma teoz true

title "HTTP without the //Host// header"

actor client
participant "DNS server\n9.9.9.9" as dns
participant "Web server 1\nwww.example.com\n93.184.216.34" as web_server_1
participant "Web server 2\nwww.github.com\n140.82.121.3" as web_server_2

client -> dns: IP for www.example.com?
dns -> client: IP for www.example.com is 93.184.216.34
client -> web_server_1: GET / HTTP/1.1
web_server_1 -> client: HTTP 200 OK

... <&clock> Time flows... ...

client -> dns: IP for www.github.com?
dns -> client: IP for www.github.com is 140.82.121.3
client -> web_server_2: GET / HTTP/1.1
web_server_2-> client: HTTP 200 OK
@enduml
