@startuml reverse-proxy

left to right direction
skinparam packageStyle rectangle
skinparam boxPadding 100
skinparam maxMessageSize 300
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250

!pragma teoz true

title "Reverse proxy"

actor "Client 1" as client1
actor "Client 2" as client2
actor "Client N" as clientN

cloud "Internet" as internet {
    (client1) -- internet
    (client2) -- internet
    (clientN) -- internet
}

rectangle "Servers LAN" as serversLan {
    actor "Server N" as serverN
    actor "Server 2" as server2
    actor "Server 1" as server1

    rectangle "Reverse proxy" as reverseProxy {
        internet -- (Enter the LAN)
        (Enter the LAN) -- server1
        (Enter the LAN) -- server2
        (Enter the LAN) -- serverN
    }
}
@enduml
