services:
  whoami-on-port-80:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    ports:
      - 80:80

  whoami-on-port-443:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    ports:
      - 443:80
