networks:
  traefik_network:
    external: true

services:
  whoami-without-stripprefix:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik_network
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      ## Routers
      - traefik.http.routers.whoami-without-stripprefix.entrypoints=https
      - traefik.http.routers.whoami-without-stripprefix.rule=Host(`${WHOAMI_FULLY_QUALIFIED_DOMAIN_NAME}`)
        && PathPrefix(`/whoami-without-stripprefix`)

  whoami-with-stripprefix:
    image: traefik/whoami:${WHOAMI_IMAGE_VERSION:-latest}
    networks:
      - traefik_network
    expose:
      - 80
    labels:
      ## Traefik
      - traefik.enable=true
      - traefik.docker.network=traefik_network
      ## Middlewares
      # We add a middleware to strip the prefix `/whoami-with-stripprefix` from the request
      - traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/whoami-with-stripprefix
      ## Routers
      - traefik.http.routers.whoami-with-stripprefix.entrypoints=https
      - traefik.http.routers.whoami-with-stripprefix.rule=Host(`${WHOAMI_FULLY_QUALIFIED_DOMAIN_NAME}`)
        && PathPrefix(`/whoami-with-stripprefix`)
      # We add the middleware created above in the middleware chain of this router
      - traefik.http.routers.whoami-with-stripprefix.middlewares=whoami-stripprefix
