@startuml java-ios-decision-tree
skinparam boxPadding 100
skinparam maxMessageSize 150
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250

title "Java IOs - Decision Tree"

start

if (Binary or Text?) then (Binary)
  :**Java IO abstract classes**

  **""InputStream""** - Read byte streams
  **""OutputStream""** - Write byte streams;

  split
    :**Files**

    **""FileInputStream""** - Read
    **""FileOutputStream""** - Write;
  split again
    :**Array of bytes**

    **""ByteArrayInputStream""** - Read
    **""ByteArrayOutputStream""** - Write;
  end split

  :**Buffering**

  **""BufferedInputStream(...)""** - Read
  **""BufferedOutputStream(...)""** - Write;

else (Text)
  : **Java IO abstract classes**

  **""Reader""** - Read characters
  **""Writer""** - Write characters;

  split
    :**Files**

    **""FileReader""** - Read
    **""FileWriter""** - Write;

  split again
    :**Strings**

    **""StringReader""** - Read
    **""StringWriter""** - Write;
  split again
    :**Array of chars**

    **""CharArrayReader""** - Read
    **""CharArrayWriter""** - Write;
  split again
    :**Text from binary**

    **""InputStreamReader""** - Bytes to chars
    **""OutputStreamWriter""** - Chars to bytes;
  end split

  :**Buffering**

  **""BufferedReader(...)""** - Read
  **""BufferedWriter(...)""** - Write;

endif
stop
@enduml
