@startuml validation-model-based-on-the-etag-header
skinparam boxPadding 100
skinparam maxMessageSize 150
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250
autonumber

!$TITLE = "Validation model based on the //ETag// header"
!$ONE_PAGE = 1

!if ($ONE_PAGE)
  ignore newpage
!else
  right footer $TITLE (%page%/%lastpage%) 
!endif

title $TITLE

participant "Client 1" as client1
participant "Client 2" as client2
participant "Server" as server
database "Database" as database

== First request by client 1 ==

note over client1, server
GET /users/1 HTTP/1.1
Host: example.com
Accept: application/json
end note
client1 -> server: Initial request (at 22 Feb 2022, 22:22:00)

|||

server -> server: Check in cache...\nCache missed; need to get the data.

note over server, database
Getting the data from the database is much slower than getting it from the cache.
end note

server -> database: Get the data...

database -> server: Return the data...

server -> server: Compute the hash of the data...

server -> server:  Store data in cache for future requests.

|||

note over client1, server
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 1024
Date: Tue, 22 Feb 2022 22:22:02 GMT
ETag: 33a64df5
end note
server -> client1: Response

client1 -> client1: Store in browser's cache.

... <&clock> Time flows... ...

newpage $TITLE

== First request by client 2 ==

note over server, client2
GET /users/1 HTTP/1.1
Host: example.com
Accept: application/json
end note
server <- client2: Initial request (at 22 Feb 2022, 22:30:00)

|||

server -> server: Check in cache...\nCache hit; data is available in the cache.

|||

note over server, client2
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 1024
Date: Tue, 22 Feb 2022 22:30:01 GMT
ETag: 33a64df5
end note
server -> client2: Response

client2 -> client2: Store in browser's cache.

... <&clock> Time flows... ...

newpage $TITLE

== Get data that have not been modified ==

|||

note over client1, server
GET /users/1 HTTP/1.1
Host: example.com
Accept: application/json
If-None-Match: 33a64df5
end note
client1 -> server: New request (at 22 Feb 2022, 23:05:00)

|||

server -> server: Check in cache...\nCache hit; data is available in the cache.

note over client1, server
HTTP/1.1 304 Not Modified
Date: Tue, 22 Feb 2022 23:05:21 GMT
end note
server -> client1: The information has not changed

client1 -> client1: Use the data in browser's cache.

... <&clock> Time flows... ...

newpage $TITLE

== Update data with no mid-air collisions (no in-between editions) ==

note over client1, server
PATCH /users/1 HTTP/1.1
Host: example.com
Accept: application/json
If-Match: 33a64df5
end note
client1 -> server: The email of the user is updated (at 22 Feb 2022, 23:15:00)

|||

server -> server: Check if no one has modified the user since Tue, 20 Feb 2022 22:00:00 GMT...\nNo modifications; the data is updated.
server -> database: Save the data...
server -> server:  Store data in cache for future requests.

|||

note over client1, server
HTTP/1.1 200 OK
Content-Type: application/json
Content-Length: 1012
Date: Tue, 22 Feb 2022 23:15:01 GMT
ETag: 84ab545e
end note
server -> client1: Response

client1 -> client1: Store in browser's cache.

... <&clock> Time flows... ...

newpage $TITLE

== Update data with mid-air collisions (in-between editions) ==

note over server, client2
PATCH /users/1 HTTP/1.1
Host: example.com
Accept: application/json
If-Match: 33a64df5
end note
client2 -> server: The username of the user is updated (at 22 Feb 2022, 23:30:00)

|||

server -> server: Check if no one has modified the user since Tue, 20 Feb 2022 22:00:00 GMT...\nModifications have occurred; invalid request.

|||

note over server, client2
HTTP/1.1 412 Precondition Failed
Date: Tue, 22 Feb 2022 23:30:01 GMT
end note
server -> client2: Response

... <&clock> Time flows... ...
@enduml
