@startuml validation-model-based-on-the-etag-header-part-4
skinparam boxPadding 100
skinparam maxMessageSize 150
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250

title "Validation model based on the ETag header - part 4/4"

participant "Client 1" as client1
participant "Server" as server
participant "Client 2" as client2

== Update data with mid-air collisions (in-between editions) ==

note over server, client2
PATCH /users/1 HTTP/1.1
Host: example.com
Accept: application/json
If-Match: 33a64df5
end note
client2 -> server: The username of the user is updated (at 22 Feb 2022, 23:30:00)

|||

server -> server: Check if no one has modified the user since Tue, 20 Feb 2022 22:00:00 GMT...\nModifications have occured; invalid request.

|||

note over server, client2
HTTP/1.1 412 Precondition Failed
Date: Tue, 22 Feb 2022 23:30:01 GMT
end note
server -> client2: Response

@enduml
