@startuml
C1->S: CONNECT alice
S->C1: OK
C2->S: CONNECT bob
S->C2: OK
C1->S: LIST
S->C1: CLIENTS alice bob
C1->S: SEND bob Hello Bob!
S->C1: OK
S->C2: RECEIVE Hello Bob! alice
C2->S: SEND alice Hello Alice!
S->C2: OK
S->C1: RECEIVE Hello Alice! bob
C1->S: QUIT
C2->S: QUIT
@enduml
