@startuml invalid-guess

title "Invalid guess example"

participant "Client" as c
participant "Server" as s

== Setup ==

c->s : Establish connection
s->s: Generate a random number\nbetween 1 and 100 (incl.).\nLet's assume 28.
c<-->s : Connection established

== Invalid guess example (out of bounds) ==

c->s: GUESS -3
s->c: ERROR 1

== Invalid guess example (not a number) ==

c->s: GUESS a
s->c: ERROR 2
@enduml
