@startuml guess-the-number-game-protocol-example-3-invalid-restart
skinparam boxPadding 100
skinparam maxMessageSize 150
skinparam noteTextAlignment center
skinparam sequenceMessageAlign direction
skinparam wrapWidth 250
autonumber

!pragma teoz true

title "Guess the number game protocol - Example 3 - Invalid restart example"

participant "Client" as c
participant "Server" as s

== Setup ==

c->s : Establish connection
s->s: Generate a random number between 1 and 100 (incl.). Let's assume 28.
c<-->s : Connection established

== Guess the number ==

c->s: GUESS 50
s->c: LOWER

c->s: RESTART
s->c: ERROR 1

c->s: GUESS 28
s->c: CORRECT

== Restart the game ==

c->s: RESTART
s->s: Generate a random number between 1 and 100 (incl.).
s->c: OK
@enduml
